using System;
using Microsoft.EntityFrameworkCore;
using TestAPI.Models;

namespace TestAPI.Enums
{
    public static class ModelExtension
    {
        public static void AddAutoGeneratedValues<T>(this ModelBuilder modelBuilder) where T : BaseModel
        {
            modelBuilder.Entity<T>().Property(d => d.Id)
                .ValueGeneratedOnAdd();

            modelBuilder.Entity<T>().Property(d => d.CreatedAt)
               .ValueGeneratedOnAdd();
            //modelBuilder.Entity<T>().Property(d => d.UpdatedAt)
            //   .ValueGeneratedOnAddOrUpdate();
            modelBuilder.Entity<T>().Property(d => d.UpdatedAt)
               .ValueGeneratedOnUpdate();
        }
    }
}
